UniinfoAsp/UniinfoAsp/Controllers/ChamadoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniinfoAsp.Models;

namespace UniinfoAsp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ChamadoController : Controller
    {
        private UnipEntities db = new UnipEntities();

        // GET: Chamado
        public ActionResult Index()
        {
            var chamadoes = db.Chamadoes.Include(c => c.Funcionario).Include(c => c.Problema);
            var cham = chamadoes.Where(c => c.statusAtendimento.Equals("Aberto"));
            return View(cham.ToList());
        }

        // GET: Chamado/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chamado chamado = db.Chamadoes.Find(id);
            if (chamado == null)
            {
                return HttpNotFound();
            }
            return View(chamado);
        }

        [HttpPost, ActionName("Details")]
        [ValidateAntiForgeryToken]
        public ActionResult DetailsDeleteConfirmed(int id)
        {
            Chamado chamado = db.Chamadoes.Find(id);
            db.Chamadoes.Remove(chamado);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        // GET: Chamado/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chamado chamado = db.Chamadoes.Find(id);
            if (chamado == null)
            {
                return HttpNotFound();
            }
            return View(chamado);
        }

        // POST: Chamado/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Chamado chamado = db.Chamadoes.Find(id);
            db.Chamadoes.Remove(chamado);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Posicionar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chamado chamado = db.Chamadoes.Find(id);
            if (chamado == null)
            {
                return HttpNotFound();
            }
            return View(chamado);
        }

        [HttpPost, ActionName("Posicionar")]
        [ValidateAntiForgeryToken]
        public ActionResult posicionarStatus(int id)
        {
            var chamado = db.Chamadoes.Find(id);
            chamado.statusAtendimento = "Em andamento";
            db.Chamadoes.Attach(chamado);
            db.Entry(chamado).Property(c => c.statusAtendimento).IsModified = true;
            db.SaveChanges();

            chamadoAtendimento ca = new chamadoAtendimento();
            ca.idChamado = chamado.idChamado;
            ca.idFuncionario = chamado.Funcionario.idFuncionario;
            db.chamadoAtendimentoes.Add(ca);
            db.SaveChanges();
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

UniinfoAsp/UniinfoAsp/Controllers/FuncController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniinfoAsp.Models;

namespace UniinfoAsp.Controllers
{
   

    [Authorize(Roles = "Funcionario")]
    public class FuncController : Controller
    {
        

        UnipEntities Db = new UnipEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CadastrarChamado()
        {

            ViewBag.funcionarioId = Db.Funcionarios.ToList();
            //ViewBag.idFuncionario = new SelectList(Db.Funcionarios.Where(x => x.nome == User.Identity.Name), "idFuncionario", "nome");
            ViewBag.problema = Db.Problemas.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult CadastrarChamado(Chamado Cham)
        {
            
                Cham.dataChamado = System.DateTime.Now;
                Cham.statusAtendimento = "Aberto";
                Db.Chamadoes.Add(Cham);
                Db.SaveChanges();
                return RedirectToAction("CadastrarChamado");

        }
    }
}

UniinfoAsp/UniinfoAsp/Controllers/LoginnController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniinfoAsp.Models;

namespace UniinfoAsp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LoginnController : Controller
    {
        private UnipEntities db = new UnipEntities();

        // GET: Loginn
        public ActionResult Index()
        {
            var loginns = db.Loginns.Include(l => l.Funcionario).Include(l => l.nivelAcesso);
            return View(loginns.ToList());
        }
        
        // GET: Loginn/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Loginn loginn = db.Loginns.Find(id);
            if (loginn == null)
            {
                return HttpNotFound();
            }
            return View(loginn);
        }

        [HttpPost, ActionName("Details")]
        [ValidateAntiForgeryToken]
        public ActionResult detailsDeleteConfirmed(int id)
        {
            Loginn loginn = db.Loginns.Find(id);
            if (loginn.login.Equals("jw"))
            {
                ViewBag.Message = "Este login não pode ser apagado";
            }
            else
            {
                db.Loginns.Remove(loginn);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(loginn);
        }
        
        // GET: Loginn/Create
        public ActionResult Create()
        {
            ViewBag.idFuncionario = new SelectList(db.Funcionarios, "idFuncionario", "nome");
            ViewBag.idNivelAcesso = new SelectList(db.nivelAcessoes, "idNivelAcesso", "tipoAcesso");
            return View();
        }

        // POST: Loginn/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idLogin,idFuncionario,login,senha,idNivelAcesso")] Loginn loginn)
        {
            if (ModelState.IsValid)
            {
                db.Loginns.Add(loginn);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idFuncionario = new SelectList(db.Funcionarios, "idFuncionario", "nome", loginn.idFuncionario);
            ViewBag.idNivelAcesso = new SelectList(db.nivelAcessoes, "idNivelAcesso", "tipoAcesso", loginn.idNivelAcesso);
            return View(loginn);
        }

        public JsonResult loginexistente(string login)
        {
            return Json(!db.Loginns.Any(l => l.login == login), JsonRequestBehavior.AllowGet);
        }

        // GET: Loginn/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Loginn loginn = db.Loginns.Find(id);
            if (loginn == null)
            {
                return HttpNotFound();
            }
            ViewBag.idFuncionario = new SelectList(db.Funcionarios, "idFuncionario", "nome", loginn.idFuncionario);
            ViewBag.idNivelAcesso = new SelectList(db.nivelAcessoes, "idNivelAcesso", "tipoAcesso", loginn.idNivelAcesso);
            return View(loginn);
        }

        // POST: Loginn/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idLogin,idFuncionario,login,senha,idNivelAcesso")] Loginn loginn)
        {
            if (ModelState.IsValid)
            {
                db.Entry(loginn).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idFuncionario = new SelectList(db.Funcionarios, "idFuncionario", "nome", loginn.idFuncionario);
            ViewBag.idNivelAcesso = new SelectList(db.nivelAcessoes, "idNivelAcesso", "tipoAcesso", loginn.idNivelAcesso);
            return View(loginn);
        }
        
        // GET: Loginn/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Loginn loginn = db.Loginns.Find(id);
            if (loginn == null)
            {
                return HttpNotFound();
            }
            return View(loginn);
        }

        // POST: Loginn/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Loginn loginn = db.Loginns.Find(id);
            if(loginn.login.Equals("jw"))
            {
                ViewBag.Message = "Este login não pode ser apagado";
            }
            else
            {
                db.Loginns.Remove(loginn);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(loginn);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UniinfoAsp/UniinfoAsp/Controllers/SobreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UniinfoAsp.Controllers
{
    public class SobreController : Controller
    {
        // GET: Sobre
        public ActionResult Index()
        {
            return View();
        }
    }
}

UniinfoAsp/UniinfoAsp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Uniinfo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <header class="bg-white py-1">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <h1>
                        <a class="navbar-brand"><img src="~/Content/images/icone.png" alt="" class="img-fluid" />@Html.ActionLink("Início", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</a>
                    </h1>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-lg-4 mr-auto">
                            <li>@Html.ActionLink("Entrar", "Login", "Account", null, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Sobre nós", "Index", "Sobre", null, new { @class = "nav-link" })</li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>

    @RenderBody()

    <!-- copyright -->
    <section style="padding:30px 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 col-md-9">
                    <p class="" style="margin-top:10px; margin-bottom:-10px;">
                        &copy; @DateTime.Now.Year - Uniinfo. Todos os direitos reservados.
                    </p>
                </div>
                <div class="col-lg-5 col-md-3">
                    <ul class="social-iconsv2 agileinfo d-flex">
                        <li>
                            <a href="#">
                                <i class="fab fa-facebook-square"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- copyright -->
</body>
</html>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)

UniinfoAsp/UniinfoAsp/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Uniinfo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header class="bg-white py-1">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <h1>
                        <a class="navbar-brand"><img src="~/Content/images/icone.png" alt="" class="img-fluid" />@Html.ActionLink("Início", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })</a>
                    </h1>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-lg-4 mr-auto">
                            <li>@Html.ActionLink("Funcionarios", "Index", "Funcionario", null, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Chamados", "Index", "Chamado", null, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Chamados em andamento", "Index", "ChamadoAtendimento", null, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Problemas", "Index", "Problema", null, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Logins", "Index", "Loginn", null, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Sair", "LogOut", "Account", null, new { @class = "nav-link" })</li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>

        @RenderBody()

    <!-- copyright -->
    <section style="padding:30px 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 col-md-9">
                    <p class="" style="margin-top:10px; margin-bottom:-10px;">
                        &copy; @DateTime.Now.Year - Uniinfo. Todos os direitos reservados.
                    </p>
                </div>
                <div class="col-lg-5 col-md-3">
                    <ul class="social-iconsv2 agileinfo d-flex">
                        <li>
                            <a href="#">
                                <i class="fab fa-facebook-square"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- copyright -->

</body>
</html>


@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)

UniinfoAsp/UniinfoAsp/Views/Shared/_LayoutFuncionario.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Uniinfo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header class="bg-white py-1">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <h1>
                        <a class="navbar-brand"><img src="~/Content/images/icone.png" alt="" class="img-fluid" />@Html.ActionLink("Início", "Index", "Func", new { area = "" }, new { @class = "navbar-brand" })</a>
                    </h1>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-lg-4 mr-auto">
                            <li>@Html.ActionLink("Chamado", "CadastrarChamado", "Func", null, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Contato", "Index", "Contato", null, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Sair", "LogOut", "Account", null, new { @class = "nav-link" })</li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>
</body>
</html>

@RenderBody()

<!-- copyright -->
<section style="padding:30px 0px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 col-md-9">
                <p class="" style="margin-top:10px; margin-bottom:-10px;">
                    &copy; @DateTime.Now.Year - Uniinfo. Todos os direitos reservados.
                </p>
            </div>
            <div class="col-lg-5 col-md-3">
                <ul class="social-iconsv2 agileinfo d-flex">
                    <li>
                        <a href="#">
                            <i class="fab fa-facebook-square"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- copyright -->
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)